-- 댓글에 대한 답변 테이블 생성 (TB_ANSWER
CREATE TABLE TB_ANSWER
(
	ANSWER_ID		INT				NOT NULL
  , ANSWER_CONTENT  VARCHAR(100)	NOT NULL
  , ANSWER_DATE		DATE			DEFAULT GETDATE()
  , BOARD_ID		INT				NOT NULL
  , REPLY_ID		INT				NOT NULL
  , U_ID			VARCHAR(200)	NOT NULL
  
  , CONSTRAINT ANSWER_ID_PK PRIMARY KEY(ANSWER_ID)
  , CONSTRAINT ANSWER_BOARDID_FK FOREIGN KEY(BOARD_ID)
			   REFERENCES TB_BOARD(BOARD_ID)
  , CONSTRAINT ANSWER_REPLYID_FK FOREIGN KEY(REPLY_ID)
			   REFERENCES TB_REPLY(REPLY_ID)
  , CONSTRAINT ANSWER_UID_FK FOREIGN KEY(U_ID)
			   REFERENCES TB_USER(U_ID)
);


SELECT *
FROM TB_REPLY;

-- ANSWER_ID 입력을 위한 서브쿼리
SELECT COUNT(*) + 1 AS [COUNT]
FROM TB_ANSWER;

-- 데이터 입력
INSERT INTO TB_ANSWER(ANSWER_ID, ANSWER_CONTENT, BOARD_ID, REPLY_ID, U_ID)
VALUES( (SELECT COUNT(*) + 1 AS [COUNT]
		 FROM TB_ANSWER), '반가워요', 12, 1, 'hskim@mostisoft.com');

INSERT INTO TB_ANSWER(ANSWER_ID, ANSWER_CONTENT, BOARD_ID, REPLY_ID, U_ID)
VALUES( (SELECT COUNT(*) + 1 AS [COUNT]
		 FROM TB_ANSWER), '반가AASDSD워요3', 197, 4, 'hskim@mostisoft.com');




-- 답변 조회를 위한 뷰 생성(REPLY_ANSWER_VIEW)
CREATE VIEW REPLY_ANSWER_VIEW
AS
SELECT A.ANSWER_ID, A.ANSWER_CONTENT, A.ANSWER_DATE, A.BOARD_ID, A.REPLY_ID, U.U_NAME
FROM TB_ANSWER A LEFT OUTER JOIN TB_USER U
     ON A.U_ID = U.U_ID;

-- 뷰 수정
ALTER VIEW REPLY_ANSWER_VIEW
AS
SELECT A.ANSWER_ID, A.ANSWER_CONTENT, A.ANSWER_DATE, A.BOARD_ID, A.REPLY_ID, A.U_ID, U.U_NAME
FROM TB_ANSWER A LEFT OUTER JOIN TB_USER U
     ON A.U_ID = U.U_ID
WHERE DEL_CHECK = 0;
--==>> Commands completed successfully.

-- 특정 게시물, 특정 답변에 대한 답글 조회
SELECT CONVERT(INT, ROW_NUMBER() OVER(ORDER BY ANSWER_ID))AS [ROWNUM], ANSWER_ID, ANSWER_CONTENT, CONVERT(VARCHAR(8), ANSWER_DATE, 112) AS [ANSWER_DATE], REPLY_ID, U_NAME, BOARD_ID
FROM REPLY_ANSWER_VIEW
WHERE BOARD_ID=194 AND REPLY_ID = 3;

SELECT *
FROM TB_REPLY;
-- 한 줄 구성
SELECT CONVERT(INT, ROW_NUMBER() OVER(ORDER BY ANSWER_ID))AS [ROWNUM], ANSWER_ID, ANSWER_CONTENT, CONVERT(VARCHAR(8), ANSWER_DATE, 112) AS [ANSWER_DATE], REPLY_ID, U_NAME, BOARD_ID FROM REPLY_ANSWER_VIEW WHERE BOARD_ID=197 AND REPLY_ID = 4
;
 
-- 특정 게시물에 특정 답변에 대한 답글 존재여부 반환 카운트 쿼리
SELECT COUNT(*) AS [COUNT] FROM REPLY_ANSWER_VIEW WHERE BOARD_ID = 197 AND REPLY_ID =7
; 

SELECT * FROM REPLY_ANSWER_VIEW WHERE BOARD_ID = 197


-- 답글조회쿼리수정
SELECT CONVERT(INT, ROW_NUMBER() OVER(ORDER BY ANSWER_ID))AS [ROWNUM], ANSWER_ID, ANSWER_CONTENT, CONVERT(VARCHAR(8), ANSWER_DATE, 112) AS [ANSWER_DATE], REPLY_ID, U_ID, U_NAME, BOARD_ID FROM REPLY_ANSWER_VIEW WHERE BOARD_ID=197 AND REPLY_ID = 7


DELETE
FROM TB_BOARD;

ALTER TABLE TB_REPLY
ADD DEL_CHECK INT DEFAULT 0;

ALTER TABLE TB_ANSWER
ADD DEL_CHECK INT DEFAULT 0;

