-- 테이블 생성 (TB_TODO)
CREATE TABLE TB_TODO
(
	TODO_ID			INT				NOT NULL
  ,	U_TODO			VARCHAR(200)	NOT NULL
  , TODO_STATUS		VARCHAR(8)		DEFAULT 'N'
  , CONSTRAINT TB_TODO__ID_PK PRIMARY KEY(TODO_ID)
  , CONSTRAINT TB_TODO_STATUS_CK CHECK(TODO_STATUS = 'Y' OR TODO_STATUS = 'N' OR TODO_STATUS = 'D' )
);
--==>> Commands completed successfully.


-- 시퀀스 생성(TODO_SEQ)
CREATE SEQUENCE TODO_SEQ 
AS DECIMAL(18, 0)
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 100
CYCLE
CACHE 1;
--==>> Commands completed successfully.

-- TB_TODO 테이블 데이터 입력
INSERT INTO TB_TODO(TODO_ID, U_TODO)
VALUES(NEXT VALUE FOR TODO_SEQ, 'ASP.NET STUDY');
--==>> (1 row affected)

INSERT INTO TB_TODO(TODO_ID, U_TODO)
VALUES(NEXT VALUE FOR TODO_SEQ, 'ASP.NET MVC STUDY');

INSERT INTO TB_TODO(TODO_ID, U_TODO)
VALUES(NEXT VALUE FOR TODO_SEQ, 'ASP.NET WINDOW FORM STUDY');

INSERT INTO TB_TODO(TODO_ID, U_TODO)
VALUES(NEXT VALUE FOR TODO_SEQ, 'ASP.NET ADO.NET STUDY');

INSERT INTO TB_TODO(TODO_ID, U_TODO)
VALUES(NEXT VALUE FOR TODO_SEQ, 'C# STUDY');

INSERT INTO TB_TODO(TODO_ID, U_TODO)
VALUES(NEXT VALUE FOR TODO_SEQ, 'JAVASCRIPT STUDY');

INSERT INTO TB_TODO(TODO_ID, U_TODO)
VALUES(NEXT VALUE FOR TODO_SEQ, 'HTML STUDY');

INSERT INTO TB_TODO(TODO_ID, U_TODO)
VALUES(NEXT VALUE FOR TODO_SEQ, 'CSS STUDY');

INSERT INTO TB_TODO(TODO_ID, U_TODO)
VALUES(NEXT VALUE FOR TODO_SEQ, 'SQL SERVER STUDY');

INSERT INTO TB_TODO(TODO_ID, U_TODO)
VALUES(NEXT VALUE FOR TODO_SEQ, 'FRAMEWORK STUDY');

-- TB_TODO 테이블 데이터 조회
SELECT *
FROM TB_TODO;
--==>> 1	ASP.NET STUDY	N

-- TB_TODO 테이블 데이터 UPDATE
UPDATE TB_TODO
SET TODO_STATUS = 'Y'
WHERE TODO_ID = 1;
--==>> (1 row affected)

-- TB_TODO 테이블 데이터 조회
SELECT *
FROM TB_TODO;

-- TB_TODO 테이블 데이터 UPDATE
UPDATE TB_TODO
SET TODO_STATUS = 'D'
WHERE TODO_ID = 1;
--==>> (1 row affected)

-- TB_TODO 테이블 데이터 조회
SELECT *
FROM TB_TODO;
--==>> 1	ASP.NET STUDY	D

-- TB_TODO 테이블 데이터 UPDATE
UPDATE TB_TODO
SET TODO_STATUS = 'L'
WHERE TODO_ID = 1;
/*
Msg 547, Level 16, State 0, Line 56
UPDATE 문이 CHECK 제약 조건 "TB_TODO_STATUS_CK"과(와) 충돌했습니다. 데이터베이스 "TEST_KSK", 테이블 "dbo.TB_TODO", column 'TODO_STATUS'에서 충돌이 발생했습니다.
문이 종료되었습니다.

--> STATUS 는 Y N D 만 존재
*/


-- TB_TODO 에서 STATUS 가 D 가 아닌것만 조회
SELECT ROW_NUMBER() OVER(ORDER BY TODO_ID ASC) AS [ROWNUM], TODO_ID, U_TODO, TODO_STATUS
FROM TB_TODO
WHERE TODO_STATUS != 'D'




