-- 답변 테이블에 추가하는 쿼리
INSERT INTO TB_ANSWER(ANSWER_ID, ANSWER_CONTENT, BOARD_ID, REPLY_ID, U_ID) VALUES( (SELECT COUNT(*)+1 AS [COUNT] FROM TB_ANSWER), ' ', BOARD_ID, REPLY_ID, U_ID  )
;

SELECT COUNT(*)+1 AS [COUNT]
FROM TB_ANSWER;

SELECT *
FROM TB_ANSWER;