-- 전체 보여지는  데이터 갯수를 구하는 쿼리
SELECT COUNT(*) AS [DATACOUNT] FROM TB_BOARD
;
-- 수정
SELECT COUNT(*) AS [DATACOUNT] FROM BOARD_LIST_VIEW2;

SELECT ROWNUM, BOARD_ID, BOARD_TITLE, BOARD_HITCOUNT, CONVERT(VARCHAR(8), BOARD_DATE, 112) AS [BOARD_DATE], BOARD_CONTENT, U_ID, U_NAME
FROM BOARD_DETAIL_VIEW2;

-- 로그인 시 이름을 띄워주기 위한 쿼리
SELECT U_NAME FROM TB_USER WHERE U_ID = 'skkim@mostisoft.com'
;

