-- BOARD_LIST_VIEW 에서 전체 조회
-- 쿼리
SELECT CONVERT(INT, ROWNUM) AS [ROWNUM], BOARD_ID, BOARD_TITLE, BOARD_HITCOUNT, CONVERT(VARCHAR(8), BOARD_DATE, 112) AS [BOARD_DATE], BOARD_CONTENT, U_NAME FROM BOARD_LIST_VIEW
WHERE BOARD_ID = 1;

SELECT CONVERT(INT, ROWNUM) AS [ROWNUM], BOARD_ID, BOARD_TITLE, BOARD_HITCOUNT, CONVERT(VARCHAR(8), BOARD_DATE, 112) AS [BOARD_DATE], BOARD_CONTENT, U_NAME FROM BOARD_LIST_VIEW WHERE BOARD_ID = 1
;


SELECT *
FROM TB_BOARD;

-- BOARD_DETAIL_VIEW 에서 특정 게시물 조회
SELECT BOARD_ID, BOARD_TITLE, BOARD_CONTENT, BOARD_HITCOUNT
     , BOARD_DATE, U_ID, U_NAME, REPLY_ID, REPLY_CONTENT, REPLY_DATE 
FROM BOARD_DETAIL_VIEW
WHERE BOARD_ID = 1;

-- 한 줄 구성
SELECT BOARD_ID, BOARD_TITLE, BOARD_CONTENT, BOARD_HITCOUNT, BOARD_DATE, U_ID, U_NAME, REPLY_ID, REPLY_CONTENT, REPLY_DATE, REPLY_U_ID FROM BOARD_DETAIL_VIEW WHERE BOARD_ID = 1

-- 따로 구성
-- BOARD_LIST_VIEW

-- REPLY_LIST_VIEW
CREATE VIEW REPLY_LIST_VIEW
AS
SELECT R.REPLY_ID, R.REPLY_CONTENT, CONVERT(VARCHAR(8), R.REPLY_DATE, 112) AS [REPLY_DATE]
     , R.BOARD_ID, U.U_NAME
FROM TB_REPLY R JOIN TB_USER U
	 ON R.U_ID = U.U_ID;

--==>> Commands completed successfully.

-- REPLY_LIST_VIEW 에서 댓글 조회
SELECT ROW_NUMBER() OVER (ORDER BY REPLY_ID) AS [ROWNUM]
     , REPLY_ID, REPLY_CONTENT, CONVERT(VARCHAR(8), REPLY_DATE, 112) AS [REPLY_DATE]
     , BOARD_ID, U_NAME
FROM REPLY_LIST_VIEW
WHERE BOARD_ID = 1;
/*
1	1	안녕하세요 저는 김효섭 이에요	20220714	1	김효섭
2	3	안녕하세요 저는 김효섭 이아니에요	20220714	1	김효섭
3	4	안녕하세요 저는 김효섭 바보에요	20220714	1	김효섭
*/

-- 한 줄 구성
SELECT ROW_NUMBER() OVER (ORDER BY REPLY_ID) AS [ROWNUM], REPLY_ID, REPLY_CONTENT, CONVERT(VARCHAR(8), REPLY_DATE, 112) AS [REPLY_DATE], BOARD_ID, U_NAME FROM REPLY_LIST_VIEW WHERE BOARD_ID = 1