-- BOARD_LIST_VIEW 에서 전체 조회
-- 쿼리
SELECT CONVERT(INT, ROWNUM) AS [ROWNUM], BOARD_ID, BOARD_TITLE, BOARD_HITCOUNT, CONVERT(VARCHAR(8), BOARD_DATE, 112) AS [BOARD_DATE], BOARD_CONTENT, U_NAME FROM BOARD_LIST_VIEW
WHERE BOARD_ID = 1;

-- 전체조회쿼리 수정(1) DEL_CHECK 이 0인것만 / ROWNUM 이 START ~ END 까지만(페이지마다 다름)
SELECT B.ROWNUM, B.BOARD_ID, B.BOARD_TITLE, B.BOARD_HITCOUNT, B.BOARD_DATE, B.U_NAME
FROM
(
SELECT CONVERT(INT, ROW_NUMBER() OVER(ORDER BY BOARD_ID)) AS [ROWNUM], BOARD_ID, BOARD_TITLE, BOARD_HITCOUNT, CONVERT(VARCHAR(8), BOARD_DATE, 112) AS [BOARD_DATE], U_NAME
FROM BOARD_LIST_VIEW WHERE DEL_CHECK = 0
)B
WHERE B.ROWNUM>=1 AND B.ROWNUM <= 10;

-- 뷰 생성
CREATE VIEW BOARD_LIST_VIEW2
AS
SELECT B.ROWNUM, B.BOARD_ID, B.BOARD_TITLE, B.BOARD_HITCOUNT, B.BOARD_DATE, B.U_NAME FROM (SELECT CONVERT(INT, ROW_NUMBER() OVER(ORDER BY BOARD_ID)) AS [ROWNUM], BOARD_ID, BOARD_TITLE, BOARD_HITCOUNT, CONVERT(VARCHAR(8), BOARD_DATE, 112) AS [BOARD_DATE], U_NAME FROM BOARD_LIST_VIEW WHERE DEL_CHECK = 0 )B

-- 한 줄 구성(최신)
SELECT ROWNUM, BOARD_ID, BOARD_TITLE, BOARD_HITCOUNT, BOARD_DATE, U_NAME FROM BOARD_LIST_VIEW2 WHERE ROWNUM >=1 AND ROWNUM <= 10
;



WHERE B.ROWNUM>=1 AND B.ROWNUM <= 10

SELECT B.ROWNUM, B.BOARD_ID, B.BOARD_TITLE, B.BOARD_HITCOUNT, CONVERT(VARCHAR(8), B.BOARD_DATE, 112) AS [BOARD_DATE], B.BOARD_CONTENT, B.U_NAME
FROM
(
SELECT CONVERT(INT, ROW_NUMBER() OVER(ORDER BY BOARD_ID)) AS [ROWNUM], U_ID, BOARD_ID, BOARD_TITLE, BOARD_HITCOUNT, CONVERT(VARCHAR(8), BOARD_DATE, 112) AS [BOARD_DATE], BOARD_CONTENT, U_NAME FROM BOARD_LIST_VIEW
)B
WHERE B.BOARD_ID = 3;

-- 특정 게시물 조회를 위한 뷰 생성
CREATE VIEW BOARD_DETAIL_VIEW2
AS
SELECT B.ROWNUM, B.BOARD_ID, B.BOARD_TITLE, B.BOARD_HITCOUNT, CONVERT(VARCHAR(8), B.BOARD_DATE, 112) AS [BOARD_DATE], B.BOARD_CONTENT, B.U_ID, B.U_NAME FROM ( SELECT CONVERT(INT, ROW_NUMBER() OVER(ORDER BY BOARD_ID)) AS [ROWNUM], BOARD_ID, BOARD_TITLE, BOARD_HITCOUNT, CONVERT(VARCHAR(8), BOARD_DATE, 112) AS [BOARD_DATE], BOARD_CONTENT, U_ID, U_NAME FROM BOARD_LIST_VIEW )B;

-- 뷰 수정(특정게시물조회를위한)
ALTER VIEW BOARD_DETAIL_VIEW2
AS
SELECT CONVERT(INT, ROW_NUMBER() OVER(ORDER BY BOARD_ID)) AS [ROWNUM], B.BOARD_ID, B.BOARD_TITLE, B.BOARD_HITCOUNT, CONVERT(VARCHAR(8), B.BOARD_DATE, 112) AS [BOARD_DATE], B.BOARD_CONTENT, B.U_ID, B.U_NAME
FROM
( 
SELECT BOARD_ID, BOARD_TITLE, BOARD_HITCOUNT, CONVERT(VARCHAR(8), BOARD_DATE, 112) AS [BOARD_DATE], BOARD_CONTENT, U_ID, U_NAME
  FROM BOARD_LIST_VIEW
  WHERE DEL_CHECK = 0 
)B;

-- 특정 게시물조회를 위한 쿼리
SELECT ROWNUM, BOARD_ID, BOARD_TITLE, BOARD_HITCOUNT, CONVERT(VARCHAR(8), BOARD_DATE, 112) AS [BOARD_DATE], BOARD_CONTENT, U_ID, U_NAME FROM BOARD_DETAIL_VIEW2 WHERE BOARD_ID = 10;



SELECT *
FROM TB_BOARD;

-- BOARD_DETAIL_VIEW 에서 특정 게시물 조회
SELECT BOARD_ID, BOARD_TITLE, BOARD_CONTENT, BOARD_HITCOUNT
     , BOARD_DATE, U_ID, U_NAME, REPLY_ID, REPLY_CONTENT, REPLY_DATE 
FROM BOARD_DETAIL_VIEW
WHERE BOARD_ID = 1;

-- 한 줄 구성
SELECT BOARD_ID, BOARD_TITLE, BOARD_CONTENT, BOARD_HITCOUNT, BOARD_DATE, U_ID, U_NAME, REPLY_ID, REPLY_CONTENT, REPLY_DATE, REPLY_U_ID FROM BOARD_DETAIL_VIEW WHERE BOARD_ID = 1

-- 따로 구성
-- BOARD_LIST_VIEW

-- REPLY_LIST_VIEW
CREATE VIEW REPLY_LIST_VIEW
AS
SELECT R.REPLY_ID, R.REPLY_CONTENT, CONVERT(VARCHAR(8), R.REPLY_DATE, 112) AS [REPLY_DATE]
     , R.BOARD_ID, U.U_NAME
FROM TB_REPLY R JOIN TB_USER U
	 ON R.U_ID = U.U_ID;

--==>> Commands completed successfully.

-- REPLY_LIST_VIEW 에서 댓글 조회
SELECT ROW_NUMBER() OVER (ORDER BY REPLY_ID) AS [ROWNUM]
     , REPLY_ID, REPLY_CONTENT, CONVERT(VARCHAR(8), REPLY_DATE, 112) AS [REPLY_DATE]
     , BOARD_ID, U_NAME
FROM REPLY_LIST_VIEW
WHERE BOARD_ID = 1;
/*
1	1	안녕하세요 저는 김효섭 이에요	20220714	1	김효섭
2	3	안녕하세요 저는 김효섭 이아니에요	20220714	1	김효섭
3	4	안녕하세요 저는 김효섭 바보에요	20220714	1	김효섭
*/

-- 한 줄 구성
SELECT ROW_NUMBER() OVER (ORDER BY REPLY_ID) AS [ROWNUM], REPLY_ID, REPLY_CONTENT, CONVERT(VARCHAR(8), REPLY_DATE, 112) AS [REPLY_DATE], BOARD_ID, U_NAME FROM REPLY_LIST_VIEW WHERE BOARD_ID = 1

SELECT CONVERT(INT, ROWNUM) AS [ROWNUM], BOARD_ID, BOARD_TITLE, BOARD_HITCOUNT, CONVERT(VARCHAR(8), BOARD_DATE, 112) AS [BOARD_DATE], BOARD_CONTENT, U_ID, U_NAME FROM BOARD_LIST_VIEW WHERE BOARD_ID = 1;

